drop table if exists categoria cascade;
drop table if exists custo cascade;
drop table if exists data cascade;
drop table if exists evento cascade;
drop table if exists evento_categoria cascade;
drop table if exists evento_tag cascade;
drop table if exists imagem cascade;
drop table if exists informacao cascade;
drop table if exists tag cascade;
drop sequence if exists seq_evento;
drop sequence if exists seq_evento_categoria;
drop sequence if exists seq_evento_custos;
drop sequence if exists seq_evento_data;
drop sequence if exists seq_evento_imagem;
drop sequence if exists seq_evento_info;
drop sequence if exists seq_evento_tags;
create sequence seq_evento start 1 increment 1;
create sequence seq_evento_categoria start 1 increment 1;
create sequence seq_evento_custos start 1 increment 1;
create sequence seq_evento_data start 1 increment 1;
create sequence seq_evento_imagem start 1 increment 1;
create sequence seq_evento_info start 1 increment 1;
create sequence seq_evento_tags start 1 increment 1;
create table categoria (id int8 not null, data_alteracao timestamp not null, data_inclusao timestamp not null, nome varchar(255), valor varchar(255), primary key (id));
create table custo (id int8 not null, data_alteracao timestamp not null, data_inclusao timestamp not null, nome varchar(255), valor numeric(19, 2), id_evento int8, primary key (id));
create table data (id int8 not null, data_alteracao timestamp not null, data_fim timestamp, data_inclusao timestamp not null, data_inicio timestamp, id_evento int8, primary key (id));
create table evento (id int8 not null, corpo_principal varchar(255), data_alteracao timestamp not null, data_inclusao timestamp not null, endereco varchar(255), link varchar(255), local varchar(255), nome varchar(255), origem_informacao varchar(255), primary key (id));
create table evento_categoria (id_evento int8 not null, id_categoria int8 not null, primary key (id_evento, id_categoria));
create table evento_tag (id_evento int8 not null, id_tag int8 not null, primary key (id_evento, id_tag));
create table imagem (id int8 not null, data_alteracao timestamp not null, data_inclusao timestamp not null, nome varchar(255), valor varchar(255), id_evento int8, primary key (id));
create table informacao (id int8 not null, data_alteracao timestamp not null, data_inclusao timestamp not null, nome varchar(255), valor varchar(255), id_evento int8, primary key (id));
create table tag (id int8 not null, data_alteracao timestamp not null, data_inclusao timestamp not null, nome varchar(255), valor varchar(255), primary key (id));
alter table custo add constraint FK6f2xtffh81j3nwug6ik7jsu1r foreign key (id_evento) references evento;
alter table data add constraint FK1ivbjgc15uivqimfwlcluiowv foreign key (id_evento) references evento;
alter table evento_categoria add constraint FK6c2001mufsoi0v49y04sp4jg1 foreign key (id_categoria) references categoria;
alter table evento_categoria add constraint FK54poapqbqlc0m0bug7cqkyhfo foreign key (id_evento) references evento;
alter table evento_tag add constraint FKs8nx0jcuscqhq7jbjht4617ut foreign key (id_tag) references tag;
alter table evento_tag add constraint FK5a2uxekklxnnorwcxidbv7l0s foreign key (id_evento) references evento;
alter table imagem add constraint FKtf3swbd1yu8hneao9y22tpsub foreign key (id_evento) references evento;
alter table informacao add constraint FKe71y376uyqehaf1homfphlvp0 foreign key (id_evento) references evento;
insert into tag (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_tags'), now(), now(), 'astronomia','Astronomia');
insert into tag (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_tags'), now(), now(), 'almoco','Almoço');
insert into tag (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_tags'), now(), now(), 'churrasco','Churrasco');
insert into tag (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_tags'), now(), now(), 'cerveja','Cerveja');
insert into categoria (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_categoria'), now(), now(), 'infantil','Infantil');
insert into categoria (id, data_inclusao, data_alteracao, nome, valor) values (nextval('seq_evento_categoria'), now(), now(), 'comer_e_beber','Comer e Beber');
insert into evento (id,link,corpo_principal, data_alteracao, data_inclusao, endereco, local, nome, origem_informacao) values (nextval('seq_evento'), 'churras_1', 'O Churras na casa do Marcão é considerado o melhor churrasco da história de Curitiba', now(), now(), 'BR 101, Km 87', 'Casa do Marcão', 'Churras 1', 'PromoCuritiba');
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '11 hours', now()::date + interval '12 hours', (select id from evento where nome = 'Churras 1'));
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '15 hours', now()::date + interval '16 hours', (select id from evento where nome = 'Churras 1'));
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '15 hours' + interval '1 day', now()::date + interval '16 hours' + interval '1 day', (select id from evento where nome = 'Churras 1'));
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '15 hours' + interval '2 days', now()::date + interval '16 hours' + interval '2 days', (select id from evento where nome = 'Churras 1'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Inteira', 50.00,(select id from evento where nome = 'Churras 1'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Crianças', 25.00,(select id from evento where nome = 'Churras 1'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Idosos', 50.00,(select id from evento where nome = 'Churras 1'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Carnes', 'Picanha, Costela, Frango',(select id from evento where nome = 'Churras 1'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Refrigerantes', 'Coca, Guaraná',(select id from evento where nome = 'Churras 1'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Cervejas', 'Trazer o que for beber',(select id from evento where nome = 'Churras 1'));
insert into imagem (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_imagem'),now(), now(), 'churras', 'img/cabin.png',(select id from evento where nome = 'Churras 1'));
insert into evento_tag (id_evento, id_tag) values ((select id from evento where nome = 'Churras 1'), (select id from tag where valor = 'Churrasco'));
insert into evento_tag (id_evento, id_tag) values ((select id from evento where nome = 'Churras 1'), (select id from tag where valor = 'Cerveja'));
insert into evento_categoria (id_evento, id_categoria) values ((select id from evento where nome = 'Churras 1'), (select id from categoria where valor = 'Comer e Beber'));
insert into evento (id,link,corpo_principal, data_alteracao, data_inclusao, endereco, local, nome, origem_informacao) values (nextval('seq_evento'),'trucostela', 'Campeonato de Truco + Costela... Tem coisa melhor?', now(), now(), 'Passaúna', 'Chácara Passaúna', 'Trucostela', 'PromoCuritiba');
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '18 hours', now()::date + interval '22 hours', (select id from evento where nome = 'Trucostela'));
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '18 hours' + interval '1 day', now()::date + interval '22 hours' + interval '1 day', (select id from evento where nome = 'Trucostela'));
insert into data (id, data_inclusao, data_alteracao, data_inicio, data_fim, id_evento) values (nextval('seq_evento_data'), now(), now(), now()::date + interval '18 hours' + interval '2 days', now()::date + interval '22 hours' + interval '2 days', (select id from evento where nome = 'Trucostela'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Inteira', 30.00,(select id from evento where nome = 'Trucostela'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Crianças', 15.00,(select id from evento where nome = 'Trucostela'));
insert into custo (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_custos'),now(), now(), 'Idosos', 30.00,(select id from evento where nome = 'Trucostela'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Carnes', 'Costela de Chão',(select id from evento where nome = 'Trucostela'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Refrigerantes', 'Coca Cola',(select id from evento where nome = 'Trucostela'));
insert into informacao (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_info'),now(), now(), 'Cervejas', 'Por conta de cada um.',(select id from evento where nome = 'Trucostela'));
insert into imagem (id, data_inclusao, data_alteracao, nome, valor, id_evento) values (nextval('seq_evento_imagem'),now(), now(), 'trucostela', 'img/cake.png',(select id from evento where nome = 'Trucostela'));
insert into evento_categoria (id_evento, id_categoria) values ((select id from evento where nome = 'Trucostela'), (select id from categoria where valor = 'Infantil'));